name: Node.js v20 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphicsmagick mediainfo exiftool

    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run coverage

    - name: Upload unit test coverage report to Codecov
      uses: codecov/codecov-action@v4