name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphicsmagick mediainfo exiftool
        gm version
        mediainfo --Version
        exiftool -ver

    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Use Node.js v24
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Lint and test
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Upload code coverage to codecov
      # https://github.com/marketplace/actions/codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.lcov